#video:
#  upload:
#    path: "uploads/videos"
#spring:
#  application:
#    name: video-service
#  config:
#    import: optional:configserver:http://localhost:9094/
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: videodb
#  cloud:
#    openfeign:
#      circuitbreaker:
#        enabled: true
##  servlet:
##    multipart:
##      max-file-size: 500MB
##      max-request-size: 500MB
#server:
#  port: 9123
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#logging:
#  level:
#    org:
#      springframework:
#        cloud: DEBUG
#        boot:
#          context:
#            config: DEBUG
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        permittedNumberOfCallsInHalfOpenState: 2
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s  # use 's' for seconds, not raw numbers



spring:
  application:
    name: video-service
  profiles:
    active:
  config:
    import: optional:configserver:http://localhost:9094/
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: videodb
server:
  port: 9123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot.context.config: DEBUG
video:
  upload:
    path: "uploads/videos"